include:
  - board: nice_nano
    shield: klor_left
    snippet: studio-rpc-usb-uart zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: nice_nano
    shield: klor_right
  - board: nice_nano
    shield: settings_reset
